name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        php-versions: ["7.3", "7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: pcov

      - name: â™»ï¸ Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: â™»ï¸ Cache composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: âš™ï¸ Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: ğŸ‘• Lint
        run: composer cs

      - name: ğŸ”¬ Static analysis
        run: composer stan

      - name: â™»ï¸ Test cache
        uses: actions/cache@v2.1.6
        with:
          path: tests/.phpunit.result.cache
          key: ${{ runner.os }}-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-

      - name: ğŸ§ª Test
        run: composer test:ci

      - name: ğŸ“Š Upload coverage results to Coveralls
        if: matrix.php-versions == '8.0'
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./build/logs/clover.xml

      - name: ğŸ“ƒ Generate documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.php-versions == '8.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
        run: |
          composer generate-docs

          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          echo `git add -A && git commit -m "docs: update documentation"`
          git push --follow-tags origin main
